<form id="co-addstep-form" action="">
<fieldset>
    <ul class="form-list">
        <li id="addstep-form">
            <fieldset>
                <ul>
                    <li class="wide">
                        <label for="addstep:like" class="required">
                            <em>*</em><?php echo $this->__('Do you like Excellence Magento Blog')?>
                        </label>
                        <div class="input-box">
                            <select class="required-entry" name="addstep[like]" id="addstep:like">
                                <option value=""><?php echo $this->__('Please Choose...')?></option>
                                <option value="1" <?php if($this->getQuote()->getAddstepLike() == 1) {echo 'selected="selected"';}?>><?php echo $this->__('Yes')?></option>
                                <option value="2" <?php if($this->getQuote()->getAddstepLike() == 2) {echo 'selected="selected"';}?>><?php echo $this->__('No')?></option>
                            </select>
                        </div>
                    </li>
                </ul>
                <div class="button-set" id="addstep-buttons-container">
                    <p class="required">
                        <?php echo $this->__('* Required Fields')?>
                    </p>
                    <button type="button" title="<?php echo $this->__('Continue')?>" class="button" onclick="addstep.save()">
                        <span><span><?php echo $this->__('Continue')?></span></span>
                    </button>
                    <span class="please-wait" id="addstep-please-wait" style="display:none;">
                        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
                    </span>
                </div>
            </fieldset>
        </li>
    </ul>
</fieldset>
</form>
<script type="text/javascript">
    //<![CDATA[
        var addstep = new AddstepMethod('co-addstep-form','<?php echo $this->getUrl('addstep/onepage/saveAddstep')?>');
        var addstepForm = new VarienForm('co-addstep-form');
    // ]]
</script>