<div class="block block-progress opc-block-progress<?php if (!$this->isCustomerLoggedIn()/* && !$this->getCheckout()->getStepData('billing', 'is_show')*/): ?> opc-block-progress-step-login<?php endif; ?>">
    <div class="block-title">
        <strong><span><?php echo $this->__('Your Checkout Progress') ?></span></strong>
    </div>
    <div class="block-content">
        <dl>
            <?php if($this->getCheckout()->getStepData('addstep', 'is_show')):?>
                <div id="addstep-progress-opcheckout">
                <?php if($this->getCheckout()->getStepData('addstep', 'complete')) : ?>
                    <dt class="complete">
                        <?php echo $this->__('Add step Review')?><span class="separator">|</span>
                        <a href="#addstep" onclick="checkout.accordion.openSection('opc-addstep'); return false;">
                            <?php echo $this->__('Change')?>
                        </a>
                    </dt>
                    <dd class="complete">
                        <div>
                            <?php
                                $like = $this->getQuote()->getAddstepLike();
                                if($like == 1) {
                                    echo $this->__('Yes');
                                } else {
                                    echo $this->__('No');
                                }
                            ?>
                        </div>
                    </dd>
                <?php else : ?>
                    <dt>
                        <?php echo $this->__('Add step Review')?>
                    </dt>
                <?php endif?>
                </div>
            <?php endif?>

            <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
                <div id="billing-progress-opcheckout">
                    <?php echo $this->getChildHtml('billing.progress') ?>
                </div>
            <?php endif; ?>

            <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
                <div id="shipping-progress-opcheckout">
                    <?php echo $this->getChildHtml('shipping.progress') ?>
                </div>
            <?php endif; ?>

            <?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
                <div id="shipping_method-progress-opcheckout">
                    <?php echo $this->getChildHtml('shippingmethod.progress') ?>
                </div>
            <?php endif; ?>

            <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
                <div id="payment-progress-opcheckout">
                    <?php echo $this->getChildHtml('payment.progress') ?>
                </div>
            <?php endif; ?>
        </dl>
    </div>
</div>